- name: Node.js را برای استفاده با اقدامات تنظیم کنید
  استفاده می کند: action/setup-node@v1.1.0
  با:
    # نسخه مشخصات نسخه برای استفاده. مثالها: 10.x ، 10.15.1 ،> = 10.15.0 ، lts
    نسخه: # اختیاری ، پیش فرض 10x است
    # رجیستری اختیاری برای تنظیم auth. رجیستری را در سطح پروژه .npmrc و پرونده .yarnrc تنظیم می کند ، و auth را برای خواندن از env.NODE_AUTH_TOKEN تنظیم می کند
    Register-url: # اختیاری
    # دامنه اختیاری برای تأیید اعتبار در برابر ثبت نام های Scoped
    دامنه: # اختیاری
